### ISSUE TITLE
补充 atob 和 btoa

### ISSUE THREAD

**Issue by iwfan** [justjavac/programming-mindmap#12]
不知 [window.atob](https://developer.mozilla.org/zh-CN/docs/Web/API/WindowBase64/atob) 和 [window.btoa](https://developer.mozilla.org/zh-CN/docs/Web/API/WindowBase64/btoa) 是否也是ECMAScript 标准里的内置属性？

如果是，希望补充进脑图。

**Comment by justjavac** [comment]
不是。

这个是 HTML 标准，不是 ecma-262(ECMAScript) 标准。
