### ISSUE TITLE
关于JS内置对象上一些不理解的地方

### ISSUE THREAD

**Issue by JackChengGZ** [justjavac/programming-mindmap#13]
1.这个全局对象跟内置对象是父子关系吗，这个全局对象是指global还是指window；
2.这个全局对象上的属性：比如全局对象的函数属性parseInt,他指向全局函数parseInt()?或者说全局对象的构造器属性Array和内置对象Array的关系是什么，当我访问Array的时候是访问属性还是内置对象Array,还是说访问的是构造器; 比如：我在控制台输出
console.log(Array)是构造函数吗还是说叫内置对象？另外console.log(Array()) 这个我没有new，算实例化吗？
3.关于Math对象和Array为啥不一样；console.log(Math) 是这样{属性...};而console.log(Array)是function

**Comment by justjavac** [comment]
这个图是根据 ECMAScript 标准 ecma262 绘制的。

全局对象 nodejs 是 `global`，浏览器是 `window`。但是标准里面只有 [`globalThis`](https://tc39.es/ecma262/#sec-global-object)。
